[tool.poetry]
name = "5e-character-sheet"
version = "0.1.0"
description = ""
authors = ["Alexander Sauceda <alexander@alexandersauceda.dev>"]
readme = "README.md"
packages = [{include = "5e_character_sheet"}]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.4.2"

[tool.pyright]
include = ["5e_character_sheet"]
venvPath = "/Users/alesauce/Workspace/5e-character-sheet/5e-character-sheet"
venv = ".venv"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
